### ISSUE TITLE
Re-enable `simple-trading-app` tests

### ISSUE THREAD

**Issue by edd** [vegaprotocol/token-frontend#1305]
#1304 disabled some tests to unblock merges. 

# Tasks
- [ ] Work out if they're valid tests
- [ ] If they are, fix 'em
- [ ] If they aren't, remove 'em
