### ISSUE TITLE
Internal networks migration from Ropsten to Sepolia

### ISSUE THREAD

**Issue by edd** [vegaprotocol/token-frontend#1307]
See https://github.com/vegaprotocol/documentation/issues/123#issue-1285546247

# Tasks
- [ ] Get contract addresses for networks on Sepolia
- [ ] Update config in all repos
- [ ] Ensure all applications work with Sepolia
